version: '3.8'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5447:5432"