spring:
  application:
    name: InternIntelligence_MovieAPI

  datasource:
    url: jdbc:postgresql://localhost:5447/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
